"""add design sections

Revision ID: ef0497006576
Revises: 3759a67a3a1a
Create Date: 2026-05-31 17:10:46.072619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0497006576'
down_revision = '3759a67a3a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_profile', schema=None) as batch_op:
        batch_op.drop_column('sections')

    # ### end Alembic commands ###
